"""first_test

Revision ID: 0e7330f23578
Revises: 
Create Date: 2018-04-24 11:08:03.503095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7330f23578'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_sku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_name', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('comment_num', sa.Integer(), nullable=True),
    sa.Column('solve_num', sa.Integer(), nullable=True),
    sa.Column('unsolve_num', sa.Integer(), nullable=True),
    sa.Column('picture_url', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_spu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spu_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_spu_spu_name'), 'problem_spu', ['spu_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_spu_spu_name'), table_name='problem_spu')
    op.drop_table('problem_spu')
    op.drop_table('problem_sku')
    # ### end Alembic commands ###
