"""empty message

Revision ID: b5255484a954
Revises: 430e7a9b280f
Create Date: 2018-04-24 14:10:24.312335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5255484a954'
down_revision = '430e7a9b280f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_type_type_name'), 'problem_type', ['type_name'], unique=False)
    op.create_index(op.f('ix_problem_sku_sku_name'), 'problem_sku', ['sku_name'], unique=False)
    op.add_column(u'problem_spu', sa.Column('sku_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problem_spu', 'problem_type', ['sku_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem_spu', type_='foreignkey')
    op.drop_column(u'problem_spu', 'sku_id')
    op.drop_index(op.f('ix_problem_sku_sku_name'), table_name='problem_sku')
    op.drop_index(op.f('ix_problem_type_type_name'), table_name='problem_type')
    op.drop_table('problem_type')
    # ### end Alembic commands ###
